# -*- coding: utf-8 -*-
"""fix notebooks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K-QRflHhIk-eX8aNkJ-gogdHn4hsQ4zs
"""

import json, glob; [open(f, 'w').write(json.dumps({**d, "metadata": {k:v for k,v in d.get("metadata",{}).items() if k!="widgets"}}, indent=1)) for f in glob.glob("*.ipynb") for d in [json.load(open(f))]]